name: trigger gitlab job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger Job
      uses: appleboy/gitlab-ci-action@master
      with:
        url: "https://gitlab.com"
        token: 9685fd3f041c3ea0889aadff0f8553
        project_id: 31733540
        debug: true
