# name: trigger gitlab job
# on: [push]
# jobs:

#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#     - name: trigger Job
#       uses: appleboy/gitlab-ci-action@master
#       with:
#         url: https://gitlab.com/bethematch/appdev/fhir-implementation-guide/github-cibmtr-ig-kick
#         ref: master
#         token: glpat-W-Gum3mBus5CGJ5x_m55
#         GITLAB_PROJECT_ID: 31733540
#         debug: true
name: Gitlab CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#  # This workflow contains a single job called "build"
  build:
#    # The type of runner that the job will run on
#    runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo run gitlab remote pipeline

      # Runs a set of commands using the runners shell
      - name: trigger pipeline
        run: curl -X POST -F token=glpat-W-Gum3mBus5CGJ5x_m55 -F ref=master https://gitlab.com/api/v4/projects/31733540/trigger/pipeline
