name: trigger gitlab job
on: [push, commit]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger Job
      uses: appleboy/gitlab-ci-action@master
      with:
        url:
        token: glpat-W-Gum3mBus5CGJ5x_m55
        project_id: 31733540
        debug: true
